name: replace_letters
description: You can replace the Arabic text and make it without letters.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  toast: ^0.3.0
  audioplayers: ^0.20.1
  easy_localization: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/pray.mp3


  fonts:
    - family: dubai
      fonts:
        - asset: assets/font/Dubai-Regular.ttf